# import aliases from `zsh_aliases`
if [ -f ~/git/config/zsh/zsh_aliases ]; then
    source ~/git/config/zsh/zsh_aliases
fi

# disable autoupdates for brew
export HOMEBREW_NO_AUTO_UPDATE=1

# enable completions
fpath=($HOME/git/config/zsh/completion $fpath)
fpath+=( /opt/homebrew/share/zsh/site-functions)
autoload -Uz compinit
compinit

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export GPG_TTY=$(tty)

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/git/config/scripts:$PATH"
export PATH="$HOME/git/whisper.cpp/build/bin:$PATH"
export PATH="/usr/local/texlive/2025basic/bin/universal-darwin/:$PATH"

export CFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"

# set BITCOIND_EXE and ELECTRS_EXE environment variables for `rust-esplora-client`
export BITCOIND_EXE="$HOME/git/config/scripts/bitcoind"
export ELECTRS_EXE="$HOME/.cargo/bin/electrs"
