# import aliases from `zsh_aliases`
if [ -f ~/git/config/zsh/zsh_aliases ]; then
    source ~/git/config/zsh/zsh_aliases
fi

# enable completions
# just completion
fpath=($HOME/git/config/zsh/completion $fpath)
autoload -Uz compinit
compinit

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export GPG_TTY=$(tty)

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/git/config/scripts:$PATH"

export CFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"
