HISTSIZE=100000
SAVEHIST=100000
HISTFILE=~/.zsh_history

# import aliases from `zsh_aliases`
if [ -f ~/git/config/zsh/zsh_aliases ]; then
    source ~/git/config/zsh/zsh_aliases
fi

# disable autoupdates for brew
export HOMEBREW_NO_AUTO_UPDATE=1

# enable completions
fpath=($HOME/git/config/zsh/completion $fpath)
fpath+=( /opt/homebrew/share/zsh/site-functions)
autoload -Uz compinit
compinit

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
export GPG_TTY=$(tty)

export BITCOIND_EXE="/opt/homebrew/bin/bitcoind"

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$HOME/git/config/scripts:$PATH"
export PATH="$HOME/git/whisper.cpp/build/bin:$PATH"
export PATH="/usr/local/texlive/2025basic/bin/universal-darwin/:$PATH"
export PATH="/opt/homebrew/opt/openjdk/bin:$PATH"
export PATH="/$HOME/.local/bin:$PATH"

export CFLAGS="-I/opt/homebrew/include"
export LDFLAGS="-L/opt/homebrew/lib"

export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

